# Generated by Django 4.1.3 on 2022-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Recently_Updated', models.DateTimeField(verbose_name='date Updated')),
                ('Date_Added', models.DateTimeField(verbose_name='date Added')),
                ('No_of_stocks', models.IntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
